"""add status column

Revision ID: 79b092660fa5
Revises: 86ff817ca649
Create Date: 2025-04-10 22:19:41.304328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b092660fa5'
down_revision = '86ff817ca649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timepages', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timepages', 'status')
    # ### end Alembic commands ###
