"""add correct column

Revision ID: 86ff817ca649
Revises: 
Create Date: 2025-04-10 21:19:36.691217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ff817ca649'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timepages', sa.Column('correct', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timepages', 'correct')
    # ### end Alembic commands ###
