"""create users table

Revision ID: 9643b819404c
Revises: 
Create Date: 2025-05-16 22:05:55.185178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9643b819404c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('users_id', sa.String(length=64), nullable=False),
    sa.Column('employment_type', sa.String(length=10), nullable=False),
    sa.Column('hourly_wage', sa.Integer(), nullable=True),
    sa.Column('fixed_wage', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('administrator', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('users_id')
    )
    op.create_table('timepages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.Time(), nullable=True),
    sa.Column('check_out', sa.Time(), nullable=True),
    sa.Column('rest_in', sa.Time(), nullable=True),
    sa.Column('rest_out', sa.Time(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timepages')
    op.drop_table('users')
    # ### end Alembic commands ###
